matrix:
  include:

    #C++ with cmake
    - os: linux
      language: cpp
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake
          script: ./scripts/runtests.bat
  